
# hro
PUT http://localhost:8081/car/1
Content-Type: application/json

  //  "price": -1,
{
  "name":"chevrolet chevelle malibu",
  "milesPerGallon":18,
  "cylinders":8,
  "displacement":307,
  "horsepower":130,
  "weightInPounds":3504,
  "acceleration":12,
  "year":"1970-01-01",
  "origin":"USA"
}

### GET request with a header
DELETE http://localhost:8081/car/3
Accept: application/json


### GET request with a header
GET https://kompsys.herokuapp.com/ip/get
Accept: application/json

### GET request with a header
GET http://localhost:8081/car/3
Accept: application/json

### GET request with a header
GET http://localhost:8081/car/
Accept: application/json

### GET request with a header
GET http://localhost:8081/car/tax?id=3
Accept: application/json