GET http://localhost:8082/calculate?price=99000&salesTax=0.19
Accept: application/json

###


POST http://localhost:8082/car
Content-Type: application/json

{
    "name":"chevrolet chevelle malibu",
    "price": 100000,
    "milesPerGallon":18,
    "cylinders":8,
    "displacement":307,
    "horsepower":130,
    "weightInPounds":3504,
    "acceleration":12,
    "year":"1970-01-01",
    "origin":"USA"
}

###
# hro
PUT http://localhost:8082/car
Content-Type: application/json

{
  "id": 12,
  "name":"cchevrolet chevelle malibu",
  "price": 100000,
  "milesPerGallon":18,
  "cylinders":8,
  "displacement":307,
  "horsepower":130,
  "weightInPounds":3504,
  "acceleration":12,
  "year":"1970-01-01",
  "origin":"USA"
}

###
POST http://localhost:8082/car
Content-Type: application/json

{
  "name":"chevrolet chevelle malibu",
  "price": 100000,
  "milesPerGallon":18,
  "cylinders":8,
  "displacement":307,
  "horsepower":130,
  "weightInPounds":3504,
  "acceleration":12,
  "year":"1970-01-01",
  "origin":"USA"
}

### GET request with a header
DELETE http://localhost:8082/car
Content-Type: application/json

{
  "id": 111
}

### GET request with a header
GET http://localhost:8082/car/all
Accept: application/json

### GET request with a header
GET http://localhost:8082/car?id=
Accept: application/json

### GET request with a header
GET http://localhost:8082/car/tax?id=3
Accept: application/json

### GET request with a header
GET http://localhost:8082/calculate?pricePreTax=300000&salesTax=0.19
Accept: application/json

###
POST http://localhost:8082/car?name=Johnny
Accept: application/json















### GET request with a header
GET https://kompsys.herokuapp.com/ip/get
Accept: application/json
